name: login_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_zoom_drawer: ^3.2.0
  font_awesome_flutter: ^10.7.0
  lottie: ^1.1.0
  provider: ^6.1.2
  string_validator: ^0.3.0
  email_validator: ^2.0.1
  image_picker: ^0.8.6
  path_provider: ^2.0.14
  shared_preferences: ^2.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/lottie/login2.json
    - assets/school1.jpg
    - assets/school2.jpg
    - assets/school3.jpg
    - assets/school4.jpg       
    - assets/school5.jpg  
    - assets/school6.jpg  
    - assets/school7.jpg
    - assets/school8.jpg
    - assets/logo.png
